version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=sqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=0000
    volumes:
      - my-db:/var/lib/mysql


  spring_app:
    image: mahasmaali/kaddem:1.0.0
    container_name: kaddem
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/kaddem\db?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    ports:
      - 8089:8089
    depends_on:
      - mysqldb

volumes:
  my-db:
    driver: local