version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  gestion-Contrat:
    build: .
    depends_on:
      - mysqldb
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "8089:8089"
    stdin_open: true
    tty: true

volumes:
  db:
