version: "3.7"
services:
  springapp:
    container_name: springboot
    build: 'C:\Users\MSI\Desktop\projetSpringBoot\projet_kaddem_bi6'
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/kaddem?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped

    image: "raouf119/kaddem:1.1"
    depends_on:
      - db-mysql

  db-mysql:
    image: "mysql:5.6"
    container_name: dbmysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      #- MYSQL_DATABASE=job
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
networks:
  springapimysql-net:

volumes:
  db: